VENV := .venv
REQS := requirements.txt
PYTHON := $(VENV)/bin/python
PIP := $(VENV)/bin/pip
OUTPUT := labels.pdf
ADDRESS := address.csv
MAIN := main.py
MAPPINGS := mappings.json

# Default target: run the script
$(OUTPUT): $(PYTHON) $(MAIN) $(ADDRESS) $(MAPPINGS)
	$(PYTHON) main.py

# Ensure virtual environment and install dependencies if needed
$(PYTHON): $(REQS)
	python3 -m venv $(VENV)
	$(PIP) install --upgrade pip
	$(PIP) install -r $(REQS)

# Clean up the virtual environment
clean:
	rm -rf $(VENV)

read: $(OUTPUT)
	open $(OUTPUT)
