VENV := .venv
REQS := requirements.txt
PYTHON := $(VENV)/bin/python
PIP := $(VENV)/bin/pip

# Default target: run the script
run: $(PYTHON) main.py
	$(PYTHON) main.py

# Ensure virtual environment and install dependencies if needed
$(PYTHON): $(REQS)
	python3 -m venv $(VENV)
	$(PIP) install --upgrade pip
	$(PIP) install -r $(REQS)

# Clean up the virtual environment
clean:
	rm -rf $(VENV)
.venv
